# Generated by Django 6.0.5 on 2026-05-28 11:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('男', '男'), ('女', '女')], max_length=2, verbose_name='性别')),
                ('id_card', models.CharField(max_length=18, unique=True, verbose_name='身份证号')),
                ('address', models.CharField(blank=True, default='', max_length=200, verbose_name='联系地址')),
            ],
            options={
                'verbose_name': '业主',
                'verbose_name_plural': '业主',
                'db_table': 'owner',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
                ('role', models.CharField(choices=[('admin', '管理员'), ('staff', '物业员工'), ('owner', '业主')], max_length=10, verbose_name='角色')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='电话')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(max_length=20, verbose_name='楼栋')),
                ('unit', models.CharField(max_length=10, verbose_name='单元')),
                ('room', models.CharField(max_length=10, verbose_name='房号')),
                ('area', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='面积(m²)')),
                ('layout', models.CharField(max_length=20, verbose_name='户型')),
                ('status', models.CharField(choices=[('occupied', '已入住'), ('vacant', '空置'), ('renovating', '装修中')], default='vacant', max_length=15, verbose_name='状态')),
                ('owner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='property.owner', verbose_name='业主')),
            ],
            options={
                'verbose_name': '房屋',
                'verbose_name_plural': '房屋',
                'db_table': 'house',
                'unique_together': {('building', 'unit', 'room')},
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='投诉/建议内容')),
                ('submit_time', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('status', models.IntegerField(choices=[(0, '待处理'), (1, '已回复')], default=0, verbose_name='状态')),
                ('reply', models.TextField(blank=True, default='', verbose_name='回复内容')),
                ('reply_time', models.DateTimeField(blank=True, null=True, verbose_name='回复时间')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.owner', verbose_name='投诉业主')),
            ],
            options={
                'verbose_name': '投诉建议',
                'verbose_name_plural': '投诉建议',
                'db_table': 'complaint',
            },
        ),
        migrations.CreateModel(
            name='Repair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='报修内容')),
                ('submit_time', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('status', models.IntegerField(choices=[(0, '待处理'), (1, '处理中'), (2, '已完成')], default=0, verbose_name='处理状态')),
                ('process_time', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('result', models.TextField(blank=True, default='', verbose_name='处理结果')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.house', verbose_name='报修房屋')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.owner', verbose_name='报修业主')),
                ('staff', models.ForeignKey(blank=True, limit_choices_to={'role': 'staff'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='property.user', verbose_name='处理员工')),
            ],
            options={
                'verbose_name': '报修',
                'verbose_name_plural': '报修',
                'db_table': 'repair',
            },
        ),
        migrations.AddField(
            model_name='owner',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='property.user', verbose_name='用户账号'),
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('publish_time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('is_public', models.BooleanField(default=True, verbose_name='业主可见')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.user', verbose_name='发布人')),
            ],
            options={
                'verbose_name': '公告',
                'verbose_name_plural': '公告',
                'db_table': 'notice',
            },
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='访客姓名')),
                ('phone', models.CharField(max_length=20, verbose_name='访客电话')),
                ('reason', models.CharField(default='探访', max_length=200, verbose_name='来访事由')),
                ('visit_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='来访时间')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.house', verbose_name='拜访房屋')),
                ('staff', models.ForeignKey(blank=True, limit_choices_to={'role': 'staff'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='property.user', verbose_name='登记员工')),
            ],
            options={
                'verbose_name': '访客',
                'verbose_name_plural': '访客',
                'db_table': 'visitor',
            },
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金额(元)')),
                ('month', models.CharField(help_text='格式: 2026-05', max_length=7, verbose_name='费用月份')),
                ('status', models.IntegerField(choices=[(0, '未缴'), (1, '已缴')], default=0, verbose_name='缴费状态')),
                ('pay_time', models.DateTimeField(blank=True, null=True, verbose_name='缴费时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.house', verbose_name='房屋')),
            ],
            options={
                'verbose_name': '物业费',
                'verbose_name_plural': '物业费',
                'db_table': 'fee',
                'unique_together': {('house', 'month')},
            },
        ),
    ]
